SCENARIOS = [
    {
        "key": "s1",
        "title": "The Idea That Lands Flat",
        "context": "You share an idea in a meeting that you think could help. No one reacts. The silence is awkward.",
        "why": "You could withdraw, push harder, or try a different way to engage. How do you respond?",
        "opts": [
            ("Clarify the problem you were trying to solve and restate your intent.", "I"),
            ("Ask for quick feedback or invite others to build on it together.", "C"),
            ("Pause and reflect: what might make others hesitant to respond?", "R"),
            ("Prototype your idea quietly and share results later.", "T"),
        ],
    },
    {
        "key": "s2",
        "title": "The Overloaded Team",
        "context": "Your team has been running on full capacity, and a new project drops in unexpectedly.",
        "why": "People are tired, but the work matters. You have to decide how to move forward.",
        "opts": [
            ("Clarify what’s truly essential and what can wait.", "I"),
            ("Re-prioritise tasks together and agree on timelines.", "C"),
            ("Ask how everyone is coping and what support they need.", "R"),
            ("Propose a new rhythm or workflow to make work more sustainable.", "T"),
        ],
    },
    {
        "key": "s3",
        "title": "The Quiet Colleague",
        "context": "A capable teammate rarely speaks up during discussions, even when you know they have good ideas.",
        "why": "You sense a missed opportunity for learning and inclusion.",
        "opts": [
            ("Check in privately to understand their comfort level.", "I"),
            ("Create smaller group discussions where everyone contributes.", "C"),
            ("Reflect on what dynamics might silence some voices.", "R"),
            ("Invite them to co-lead a small task to build confidence.", "T"),
        ],
    },
    {
        "key": "s4",
        "title": "The Missing Context",
        "context": "You’re added to a project halfway through. Goals and decisions are unclear, but deadlines are close.",
        "why": "You could act fast, or slow down to orient yourself.",
        "opts": [
            ("Ask for clarity on purpose, roles, and current status.", "I"),
            ("Set up a short sync to align everyone quickly.", "C"),
            ("Observe for a bit to understand group patterns.", "R"),
            ("Sketch a quick summary of what’s known and test it with the group.", "T"),
        ],
    },
    {
        "key": "s5",
        "title": "The Tech Shortcut",
        "context": "A new AI tool could save hours of manual work, but no one has tested it yet.",
        "why": "You sense potential, but also the risk of wasting time if it fails.",
        "opts": [
            ("Clarify what success looks like before adopting the tool.", "I"),
            ("Run a short trial with clear check-in points.", "C"),
            ("Ask why people hesitate and what concerns they have.", "R"),
            ("Test it on one process and share what you learn.", "T"),
        ],
    },
    {
        "key": "s6",
        "title": "The Feedback Moment",
        "context": "A peer asks, 'Be honest — how was my presentation?' You saw both strengths and gaps.",
        "why": "It’s a chance to help, but you’re unsure how direct to be.",
        "opts": [
            ("Ask what kind of feedback they’d find most useful first.", "I"),
            ("Use a simple framework to share both positives and improvements.", "C"),
            ("Reflect on why giving feedback feels tricky for you.", "R"),
            ("Offer to practise together before their next presentation.", "T"),
        ],
    },
    {
        "key": "s7",
        "title": "The Sticky Stakeholder",
        "context": "A senior stakeholder keeps changing direction. The team’s energy is fading.",
        "why": "You could comply, challenge, or help the system make sense of itself.",
        "opts": [
            ("Clarify expectations and what success means this round.", "I"),
            ("Summarise changes and confirm decisions in writing.", "C"),
            ("Explore why priorities keep shifting — what pressures exist upstream?", "R"),
            ("Co-create a shared decision tracker or playbook for future projects.", "T"),
        ],
    },
    {
        "key": "s8",
        "title": "The Missed Deadline",
        "context": "A deliverable slips, affecting others. You weren’t solely at fault, but you were part of it.",
        "why": "It’s a test of accountability and learning culture.",
        "opts": [
            ("Acknowledge the miss and clarify your part.", "I"),
            ("Meet quickly with affected teams to reset timelines.", "C"),
            ("Ask what blind spots or assumptions contributed.", "R"),
            ("Share lessons learnt and suggest how to avoid repeats.", "T"),
        ],
    },
    {
        "key": "s9",
        "title": "The Team Debate",
        "context": "Two teammates strongly disagree on an approach — one wants structure, the other prefers experimentation.",
        "why": "Both have valid points. You’re caught in the middle.",
        "opts": [
            ("Clarify what problem we’re really solving before choosing.", "I"),
            ("Agree on next steps: try one approach with review points.", "C"),
            ("Ask each to explain the principle behind their view.", "R"),
            ("Combine both ideas into a short pilot to test outcomes.", "T"),
        ],
    },
    {
        "key": "s10",
        "title": "The Change Rollout",
        "context": "A new policy launches and complaints flood in: 'Another change again?'",
        "why": "Change fatigue is real, but the change matters.",
        "opts": [
            ("Clarify what the change fixes and what stays the same.", "I"),
            ("Create a quick Q&A resource and feedback loop.", "C"),
            ("Ask what worries people most about new changes.", "R"),
            ("Turn early feedback into tweaks that show responsiveness.", "T"),
        ],
    },
    {
        "key": "s11",
        "title": "The Sustainability Trade-Off",
        "context": "Your company wants to go greener, but sustainable materials slow production and raise costs.",
        "why": "Short-term targets clash with long-term commitments.",
        "opts": [
            ("Define what 'sustainability' really means in this context.", "I"),
            ("Bring Finance, Ops, and Sustainability together to review trade-offs.", "C"),
            ("Hold a dialogue on what 'responsible growth' means for the team.", "R"),
            ("Pilot a lower-impact process and measure both cost and learning.", "T"),
        ],
    },
    {
        "key": "s12",
        "title": "The Small Win",
        "context": "The team just completed a tough sprint. Everyone rushes to the next task.",
        "why": "Celebration feels like a luxury, but reflection builds capability.",
        "opts": [
            ("Acknowledge what went well and who made it happen.", "I"),
            ("Create a five-minute retrospective at the next stand-up.", "C"),
            ("Ask what surprised or challenged people most.", "R"),
            ("Turn insights into a new team ritual for learning and gratitude.", "T"),
        ],
    },
]